### ISSUE TITLE
Ugly UI after updating from 6.3.x to 6.4.x

### ISSUE THREAD

**Issue by andrewhotlab** [freebsd/freebsd-ports-libreoffice#10]
I do not know if this is the better place to spot this issue, please redirect me to the right one eventually...

After upgrading from FreeBSD quarterly pkg repository, the UI looks a bit ugly:

![Screenshot_2020-07-16_10-16-25](https://user-images.githubusercontent.com/26433166/87657245-db647780-c75a-11ea-912f-188d6d77dca6.png)

![Screenshot_2020-07-16_11-38-37](https://user-images.githubusercontent.com/26433166/87657255-df909500-c75a-11ea-9902-8303bf314a12.png)

It looks like to me that it is not only related to fonts, but something about graphic engine... unfortunately I do not have the clue to give you any better guess at this time.

I was able to reproduce it with different DE (XFCE, Mate) and themes, FreeBSD releases (11.4, 12.1), architectures (i386, amd64) and video cards.

Thanks for any suggestion, and many thanks for your work to bring LibreOffice to the small but strong minority of us, FreeBSD desktop users! ;)

**Comment by lwhsu** [comment]
If possible, please report to https://lists.freebsd.org/mailman/listinfo/freebsd-office and https://lists.freebsd.org/mailman/listinfo/freebsd-ports list as there are more people can join the discussion.

**Comment by lwhsu** [comment]
This is highly due to the VCL backend has been changed to qt5 from gtk2. Unfortunately, gtk3 is more buggy at the moment and gtk2 is dropped by 6.4 so it looks we should stay with qt5 it for a while.

**Comment by lwhsu** [comment]
Also, please help test 7.0 https://lists.freebsd.org/pipermail/freebsd-office/2020-July/005822.html
